### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by zfk513** [nex3z/tfmobile-mnist-android#1]

**Comment by zfk513** [comment]
hi there,i just cannot build the apk
![image](https://user-images.githubusercontent.com/29036702/40981127-c8eb125c-690c-11e8-9f89-7de9d5a2b1d3.png)
and i cannot install the prebuild apk as well because of the signature ,although i use the lucky patcher

**Comment by zfk513** [comment]
![image](https://user-images.githubusercontent.com/29036702/40981186-f09a2996-690c-11e8-9176-77c57e54db85.png)

**Comment by nex3z** [comment]
你打开的是 `tfmobile-mnist-android`，这个不是 Android Studio 项目工程。`tfmobile-mnist-android` 下的 `android` 文件夹内是 Android Studio 项目工程。

![40981127-c8eb125c-690c-11e8-9f89-7de9d5a2b1d3](https://user-images.githubusercontent.com/5645004/40981787-67927db8-690e-11e8-9edd-10506459ad7d.png)
