### ISSUE TITLE
识别结果

### ISSUE THREAD

**Issue by awsssix** [nex3z/tfmobile-mnist-android#3]
@nex3z 你好，我在你的代码基础上进行修改，为什么python测试结果，和Android测试结果不同，有可能是因为什么呢？识别如下图片：
![image](https://user-images.githubusercontent.com/46213799/63740486-c91fe780-c8c3-11e9-9dfe-7a9a85edaf60.png)
使用相同的pb模型，Python代码识别结果：
![image](https://user-images.githubusercontent.com/46213799/63740469-be655280-c8c3-11e9-9a47-d9eede1f8d09.png)
Android识别结果：
![image](https://user-images.githubusercontent.com/46213799/63740461-b6a5ae00-c8c3-11e9-9901-3e923897a627.png)

**Comment by nex3z** [comment]
建议首先检查一下 python 和 Android 运行模型时，模型的直接输入是否一致。在将数据输入模型之前，通常会有一些预处理，如将 RGB 图片转换为灰度等。如果在 python 和 Android 上对预处理步骤的实现或计算精度有差异，可能会导致同一张图片在预处理后的结果有微小差异，从而影响模型输出。

如果确认在 python 和 Android 上模型的直接输入完全相同，但是模型的输出不一致，可能是 TensorFlow Mobile 的实现与 TensorFlow 有差异，导致对相同输入产生不同的输出。

在实践中，通常会对用于移动端的模型中的参数进行量化，来降低模型体积、提高计算速度。如果进行了量化，则量化模型和原始模型在性能上有一定差异是正常的。

**Comment by awsssix** [comment]
@awsssix 
现在测试，中文没问题，主要是英文识别，字符会重叠输出，如with被识别为wiithh等
而且pb文件是同一个，也没有量化，预处理麻烦您看一下有没有问题
Python预处理：
![image](https://user-images.githubusercontent.com/46213799/63748064-312df800-c8db-11e9-8214-7da49cffdf09.png)
Android预处理：
![image](https://user-images.githubusercontent.com/46213799/63748214-8538dc80-c8db-11e9-8d26-ffe3931da9c9.png)
![image](https://user-images.githubusercontent.com/46213799/63748259-98e44300-c8db-11e9-8eb6-94a674be9532.png)

**Comment by awsssix** [comment]
@nex3z 我已解决，谢谢
我还有一个问题想问问您，Android做OCR识别如何提高速度，除了尽可能的少用for循环，还有其他思路吗

**Comment by nex3z** [comment]
首先要找到性能瓶颈。比如在预处理各个关键步骤，以及模型运行前后加上日志，计算各步骤耗时，针对耗时步骤进行特定的优化。

如果用的是 TensorFlow Mobile，估计瓶颈是在 TensorFlow Mobile 执行模型预测上，这个只能从优化模型的角度入手。比如简化模型结构，对模型进行量化等，虽然会损耗一定的精度，但会提升运行速度。

**Comment by awsssix** [comment]
@awsssix 非常感谢，按照你说的思路，我发现水平投影使用两个for循环比较耗时，Android开发可以用什么方法，计算二维图像的每行的和，得到一个列向量

**Comment by nex3z** [comment]
可以找找看是否有专门进行对矩阵运算进行优化的 Java 库，或者直接用 C 实现。

另外 Android 的 [RenderScript](https://developer.android.com/guide/topics/renderscript/compute) 也适合用来实现运算密集的任务，它提供了一系列[矩阵运算的方法](https://developer.android.com/guide/topics/renderscript/reference/rs_matrix)。可以找下是否有对矩阵各行求和的现成的方法，或者直接计算（比如用矩阵乘以一列全 1 的向量）。我并没有实际使用过 RenderScript，具体性能需要在实践中检验。

**Comment by awsssix** [comment]
@nex3z 
你好，我还有个问题，如果代码、模型没问题，但电脑端和移动端识别结果有差别，可能是因为手机分辨率造成的吗，，还是应该继续查找代码的问题

**Comment by nex3z** [comment]
使用同一张图片，并确保电脑端和移动端模型的直接输入一致，然后就可以使用[前面](https://github.com/nex3z/tfmobile-mnist-android/issues/3#issuecomment-525157909)的方法排查。

如果电脑端和移动端模型使用的是不同的图片，例如电脑使用相机拍摄的图片，移动端使用手机拍摄的图片，则无法直接比较模型性能，需要控制实验变量。
