### ISSUE TITLE
转圈等待

### ISSUE THREAD

**Issue by awsssix** [nex3z/tfmobile-mnist-android#4]
@nex3z 
      你好，现在我做了两个界面（fragment），一个上传图片fragmentA，一个显示识别结果fragmentB：
     1）A上传相册图片之后，就回到A界面，
    2）然后在A对图片进行识别，并转圈等待，显示正在识别
    3）识别完成，跳转到B
您能跟我说一下大概思路吗，我尝试着不行，谢谢

**Comment by nex3z** [comment]
传统方法：
1. Classifier 放在 Activity 里，进行初始化。
2. Activity 展示 Fragment A。
3. Fragment A 从 Activity 获取 Classifier 实例。
4. 用户上传图片，Fragment A 在后台（Handler / Thread 等）使用 Classifier 进行异步检测，展示转圈等待。
4. 检测完成，Fragment A 将结果发给 Activity；Activity 收到检测结果，展示 Fragment B。
5. Fragment B 展示检测结果。


使用 [Jetpack](https://developer.android.google.cn/jetpack?hl=zh_cn)：
1. Classifier 放在 [ViewModel](https://developer.android.google.cn/topic/libraries/architecture/viewmodel?hl=zh_cn) 里，进行初始化。Activity、Fragment A、Fragment B 共享同一个 ViewModel；Classifier 检测结果通过 [LiveData](https://developer.android.google.cn/topic/libraries/architecture/livedata?hl=zh_cn) 输出。
2. Activity 中使用 [Navigation](https://developer.android.google.cn/guide/navigation/?hl=zh_cn) 展示 Fragment A。
3. 用户上传图片，Fragment A 通过 ViewModel 在使用 Classifier 后台（Handler / Thread 等）进行异步检测，展示转圈等待。
4. 检测完成，Fragment A 通过 LiveData 收到检测结果，使用 Navigation 切换到 Fragment B。
5. Fragment B 通过 LiveData 获取检测结果，进行展示。

**Comment by awsssix** [comment]
@nex3z 非常感谢，解决了
可以再向您请教个问题吗，调用系统相机后，预览的时候，如何加上图片裁剪、旋转功能

**Comment by nex3z** [comment]
可以使用 Jetpack 的 [CameraX](https://developer.android.google.cn/training/camerax?hl=zh_cn) 来操作摄像头。[旋转](https://developer.android.google.cn/training/camerax/configuration?hl=zh_cn#rotation)是可以直接配置的。如果[指定分辨率](https://developer.android.google.cn/training/camerax/configuration?hl=zh_cn#specify-resolution)不满足要求，要进行裁剪，就需要自己实现了。
